version: "3"
services:
  db:
    restart: always
    image: postgres:14
    container_name: sqltutor_db_1
    env_file:
      - ./env

  sqltutor:
    restart: always
    build: sqltutor/
    image: sqltutor
    container_name: sqltutor_1
    ports:
      - 8085:80
    env_file:
      - ./env
