services:
  db:
    restart: always
    image: postgres:16
    container_name: sqltutor_db_1
    volumes:
      - db_data:/var/lib/postgresql/data
    env_file:
      - ./env

  sqltutor:
    restart: always
    build: sqltutor/
    image: sqltutor
    container_name: sqltutor_1
    ports:
      - 8085:80
    env_file:
      - ./env

volumes:
  db_data:
